//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLibrary.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataEFEntity : DbContext
    {
        public DataEFEntity()
            : base("name=DataEFEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CentralConfig> CentralConfigSet { get; set; }
        public virtual DbSet<HostContext> HostContextSet { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Solution> Solutions { get; set; }
        public virtual DbSet<Plc> Plcs { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<DataBase> DataBases { get; set; }
        public virtual DbSet<PlcList> PlcLists { get; set; }
        public virtual DbSet<ProjectList> ProjectLists { get; set; }
        public virtual DbSet<DataBaseList> DataBaseLists { get; set; }
    }
}
