//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//第二部分
using System;
using System.Collections.Generic;

namespace DataAccessLibrary.Model
{
    public partial class DataBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DataBase()
        {
            this.DataBaseLists = new HashSet<DataBaseList>();
        }
    
        public int Id { get; set; }
        public int SolutionId { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
    
        public virtual Solution Solution { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataBaseList> DataBaseLists { get; set; }
    }
}
