//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//第二部分
using System;
using System.Collections.Generic;

namespace DataAccessLibrary.Model
{
    public partial class HostContext
    {
        public int Id { get; set; }
        public int CentralConfigId { get; set; }
        public short ModelId { get; set; }
        public string ModelType { get; set; }
        public string ModelParameter { get; set; }
    
        public virtual CentralConfig CentralConfig { get; set; }
    }
}
