//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

//第二部分
using System;
using System.Collections.Generic;

namespace DataAccessLibrary.Model
{
    public partial class HostContext
    {
        public int Id { get; set; }
        public int CentralConfigId { get; set; }
        public short ModelId { get; set; }
        public string ModelType { get; set; }
        public string ModelParameter { get; set; }
    
        public virtual CentralConfig CentralConfig { get; set; }
    }
}
