//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

//第二部分
using System;
using System.Collections.Generic;

namespace DataAccessLibrary.Model
{
    public partial class PlcList
    {
        public int Id { get; set; }
        public int PlcId { get; set; }
        public string PlceListName { get; set; }
        public string PlceListParas { get; set; }
        public string PlceListComponent { get; set; }
    
        public virtual Plc Plc { get; set; }
    }
}
